---
- name: Monitor Docker Infrastructure
  hosts: docker_hosts
  become: yes
  
  tasks:
    - name: Get container statistics
      command: docker stats --no-stream --format "table {% raw %}{{.Name}}\t{{.CPUPerc}}\t{{.MemUsage}}\t{{.NetIO}}{% endraw %}"
      register: container_stats
      changed_when: false
    
    - name: Display container stats
      debug:
        var: container_stats.stdout_lines
    
    - name: Get disk usage
      command: docker system df
      register: disk_usage
      changed_when: false
    
    - name: Display disk usage
      debug:
        var: disk_usage.stdout_lines
    
    - name: List running containers
      command: docker ps --format "table {% raw %}{{.Names}}\t{{.Status}}\t{{.Ports}}{% endraw %}"
      register: running_containers
      changed_when: false
    
    - name: Display running containers
      debug:
        var: running_containers.stdout_lines
